/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppInfo {
  'id' : string,
  'name' : string,
  'description' : string,
  'pricingModel' : PricingModel,
}
export interface BlogGeneratorInput {
  'topic' : string,
  'tone' : string,
  'targetAudience' : string,
}
export interface BlogGeneratorOutput {
  'wordCount' : bigint,
  'article' : string,
}
export interface FounderProfile {
  'bio' : string,
  'missionStatement' : string,
  'title' : string,
  'name' : string,
  'coreSkills' : string,
}
export interface GeneratedContent {
  'output' : BlogGeneratorOutput,
  'appId' : string,
  'timestamp' : bigint,
  'input' : BlogGeneratorInput,
}
export interface ImplementationGoal {
  'goalName' : string,
  'useCase' : string,
  'example' : string,
}
export interface ImplementationLibrary {
  'futureGoals' : Array<ImplementationGoal>,
  'goals' : Array<ImplementationGoal>,
}
export type PricingModel = { 'credits' : { 'pricePerCreditCents' : bigint } } |
  { 'subscription' : { 'monthlyPriceCents' : bigint } } |
  { 'oneTime' : { 'priceCents' : bigint } };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StressTestMetrics {
  'applicationsTested' : bigint,
  'peakLoad' : bigint,
  'optimizationRecommendations' : string,
  'completionTimeMs' : bigint,
  'successRate' : bigint,
  'bottlenecksDetected' : bigint,
  'errorRate' : bigint,
  'latencyMs' : bigint,
  'workflowStagesTested' : bigint,
  'simulatedUsers' : bigint,
  'memoryUsageMb' : bigint,
  'throughputRps' : bigint,
  'reportInsights' : string,
  'averageResponseTimeMs' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionStatus {
  'status' : string,
  'nextBillingDate' : bigint,
  'monthlyPriceCents' : bigint,
  'appId' : string,
  'startDate' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'credits' : bigint,
  'name' : string,
  'email' : string,
  'subscriptionStatus' : [] | [SubscriptionStatus],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFutureImplementationGoal' : ActorMethod<[ImplementationGoal], undefined>,
  'addImplementationGoal' : ActorMethod<[ImplementationGoal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getApps' : ActorMethod<[], Array<AppInfo>>,
  'getCallerGeneratedContent' : ActorMethod<[], Array<GeneratedContent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultImplementationGoals' : ActorMethod<[], Array<ImplementationGoal>>,
  'getDefaultStressTestMetrics' : ActorMethod<[], StressTestMetrics>,
  'getFounderProfile' : ActorMethod<[], FounderProfile>,
  'getImplementationGoals' : ActorMethod<[], Array<ImplementationGoal>>,
  'getImplementationLibrary' : ActorMethod<[], ImplementationLibrary>,
  'getLastStressTestResults' : ActorMethod<[], [] | [StressTestMetrics]>,
  'getStressTestMetricsHistory' : ActorMethod<[], Array<StressTestMetrics>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeImplementationGoal' : ActorMethod<[string], undefined>,
  'runStressTest' : ActorMethod<[], StressTestMetrics>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGeneratedContent' : ActorMethod<[GeneratedContent], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];